# Generated by Django 5.2.8 on 2026-01-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_player_approved_at_player_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
