# Generated by Django 5.2.8 on 2026-01-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_alter_player_age_alter_player_name_and_more'),
    ]

    operations = [
    ]
